#include <iostream>
#include <filesystem>
#include <opencv2/opencv.hpp>

#include "example.h"
// rust library header generated by cxx (<BRIDGE_SRC>.rs.h)
#include "opencv_ffi.rs.h"

using namespace std;


void try_pure_cpp(const string &img_path)
{
    cout << "This is a pure C++ function." << endl;

    cv::Mat image = cv::imread(img_path);
    if (image.empty())
    {
        throw_error("Could not open or find the image!");
    }

    cv::Mat flipped_image = flip_image(image);

    cv::imshow("Pure C++", image);
    cv::imshow("Pure C++ Flipped", flipped_image);
    cv::waitKey(0);
    cv::destroyAllWindows();
    cout << "Image loaded successfully! Image size: " << image.cols << "x" << image.rows << "\n";
}

void try_mix_cpp_rust(const string &img_path)
{
    cout << "This is a mixed C++ and Rust function." << endl;

    cv::Mat image = cv::imread(img_path);
    if (image.empty())
    {
        throw_error("Could not open or find the image!");
    }

    cv::Mat resized_image = *resize_image_rust(image, 300, 300);

    cv::imshow("Mixed C++ and Rust", image);
    cv::imshow("Mixed C++ and Rust Resized", resized_image);
    cv::waitKey(0);
    cv::destroyAllWindows();
    cout << "Image loaded successfully! Image size: " << image.cols << "x" << image.rows << "\n";   
}


int main(int, char **)
{
    string project_root = PROJECT_ROOT;
    filesystem::path img_path1 = filesystem::path(project_root).append("assets/01.png");
    filesystem::path img_path2 = filesystem::path(project_root).append("assets/02.jpg");
    assert_file_exists(img_path1);
    assert_file_exists(img_path2);

    try_pure_cpp(img_path1.string());
    try_mix_cpp_rust(img_path2.string());
    return 0;
}